name: Show Events on Release
on:
  release:
    types: [created]
  workflow_dispatch:
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: "display github context"
        run: echo '${{ toJSON(github.event) }}' | jq
